-- Magnitude Analysis

-- Compare the measure values by categories

-- Find Total  customers by countries
-- Find total customers by gender
-- Find Total products by category
-- What is the average costs in each category
-- What is the total revenue generated for each category
-- Find total revenue is generated by each customer
-- What is the distribution of sold items across countries


SELECT DISTINCT
country,
COUNT(customer_key) OVER (PARTITION BY country) AS customer_by_countries
FROM gold.dim_customers
ORDER BY customer_by_countries DESC


SELECT 
gender,
COUNT(customer_key) AS customer_by_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY customer_by_gender DESC


SELECT category,
COUNT(product_key) AS product_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY product_by_category DESC


SELECT category,
AVG(cost) AS avgCost_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY avgCost_by_category DESC


SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue	
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC


SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue	
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC





SELECT 
	c.country,
	SUM(f.quantity) AS total_sold_items	
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC










